name: 🚀

on:
  push:
    branches:
      - main

permissions:
  contents: write # to be able to publish a GitHub release
  issues: write # to be able to comment on released issues
  pull-requests: write # to be able to comment on released pull requests
  id-token: write # to enable use of OIDC for npm provenance

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ github.token }}
      - uses: actions/setup-node@v3
        with:
          node-version: '22'
      - name: Build
        run: |
          corepack enable
          pnpm install --frozen-lockfile --ignore-scripts
          pnpm build
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}
      - name: Release
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          npx semantic-release
        env:
          GH_TOKEN: ${{ github.token }}}
          NPM_TOKEN: ${{ github.token }}
